#ifndef RPC_H
#define RPC_H

enum {
    RPC_SEND_FILES_LIST = 1,
    RPC_CHANGE_DIRECTORY,
    RPC_DOWNLOAD_FILE,
    RPC_SEND_FILE,
    RPC_UPLOAD_FILE,
    RPC_UPLOAD_FILE_FINISHED,
    RPC_DELETE_FILE,
};

#endif // RPC_H
